name: Update database

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install .

      - name: Update database
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: python scripts/update_db.py
